---

- name: check freebsd agent available
  shell: ssh-add -l | grep -i freebsd
  ignore_errors: true
  register: freebsd_loaded

- name: manage sources
  vars:
    ssh_agent_enabled: "{{ lookup('env', 'SSH_AUTH_SOCK') }}"

  block:
    - name: create svn folder
      file: state=directory path={{ ansible_user_dir }}/svn mode=0755

    - name: checkout svn repository
      shell: |
          cd {{ ansible_user_dir }}/svn && svn checkout -q {{ freebsd_src }} src
          cd {{ ansible_user_dir }}/svn && svn checkout -q {{ freebsd_port }} ports

    - name: update svn repository
      shell: |
        cd {{ ansible_user_dir }}/svn && svn up src ports
  when: ssh_agent_enabled is defined and not freebsd_loaded.failed
