---

- name: install minimal packages
  become: true
  action: package pkg={{ item }} state=present
  with_items:
      - python3
      - vim-console
      - vifm
      - htop
      - tmux
      - mosh
      - curl
      - wget
      - sudo
      - p5-libwww
      - p5-LWP-Protocol-https
      - lsof
      - bash
      - pftop
      - iftop
      - the_silver_searcher
      - cmdwatch
      - mtr-nox11
      - tree
      - lscpu
      - pciutils
      - pciids
      - usbutils
      - usbids

- name: install developers packages
  become: true
  action: package pkg={{ item }} state=present
  with_items:
      - arcanist-php73
      - colordiff
      - git
      - git-extras
      - jq
      - portlint
      - porttools
      - poudriere
      - py??-python-bugzilla
      - subversion
      - tig
      - psearch
