---

- name: install minimal packages
  become: true
  action: package pkg={{ item }} state=present
  with_items:
      - python3
      - vim
      - vifm
      - htop
      - tmux
      - mosh
      - curl
      - wget
      - sudo
      - p5-libwww
      - p5-LWP-Protocol-https
      - lsof
      - bash
      - pftop
      - iftop
      - the_silver_searcher

- name: install developers packages
  become: true
  action: package pkg={{ item }} state=present
  with_items:
      - arcanist-php73
      - colordiff
      - git
      - portlint
      - porttools
      - poudriere
      - subversion
      - tig  
