---
packages:
  - barrier
  - bash-completion
  - bash-static
  - colordiff
  - cscope
  - curl
  - dmidecode
  - fping
  - git
  - git-extras
  - htop
  - iftop
  - jq
  - lsblk
  - lscpu
  - lsof
  - ltrace
  - mosh
  - ngrep
  - python311
  - rsync
  - subversion
  - synergy
  - the_silver_searcher
  - tig
  - tmux
  - usbutils
  - vifm
  - vim
  - pass

x11_packages:
  - dmenu
  - drm-kmod
  - feh
  - i3
  - i3lock
  - i3status
  - pwcview
  - rxvt-unicode
  - webcamd
  - xauth
  - xf86-input-keyboard
  - xf86-input-mouse
  - xf86-input-synaptics
  - xf86-video-intel
  - xf86-video-vesa
  - xinit
  - xkill
  - xorg-drivers
  - xorg-fonts
  - xorg-server
  - xrandr
  - xrdb
  - xset
  - xterm

extra_packages:
  - gcc
  - gcc-arm-embbeded
  - gdb
  - portfmt
  - portlint
  - portsnap
  - poudriere
  - gnupg
  - firefox
  - w3m
  - rustup
  - ncdu
  - mtr
  - pinentry-curses
  - mutt

sbz_home_dir: "/home/sbz"
