 - name: install packages
   action: package name={{ item }} state=present
   with_items: 
     - "{{ packages }}"

 - name: install X11 packages
   action: package name={{ item }} state=present
   with_items: 
     - "{{ x11_packages }}"
